# version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "abhiram"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "problemhunt"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  # ffmpeg:
  #   image: jrottenberg/ffmpeg:4.1-alpine
  #   container_name: ffmpeg
  #   restart: always
  #   volumes:
  #     - ffmpeg_data:/data
  #   networks:
  #     - app-network

volumes:
  pgdata:
  minio_data:
  # ffmpeg_data:

networks:
  app-network:
    driver: bridge
