import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
// import Navbar from "@/components/Navbar";
import ClientWrapper from "@/components/ClientWrapper";
import MainComponent from "@/components/MainComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} h-screen max-w-[1400px] mx-auto border-l-2 border-r-2 border-violet-800 flex flex-col ${geistMono.variable} antialiased`}
      >
        <MainComponent>
          {/* <Navbar /> */}
          <div className="flex">
            <Sidebar />
            <ClientWrapper>{children}</ClientWrapper>
          </div>
        </MainComponent>
      </body>
    </html>
  );
}
